# -*- coding: utf-8 -*-
"""EdunetDay3(8thJuly2026).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxXlFzEErEZnXP-TPAdhqjmNr9H6yyWA
"""

#range

print("This is loop 1")
for i in range(4):
  print(i)

print("This is loop 2")
for i in range(4,8):
  print(i)

print("This is loop 3")
for i in range(8,12,2):
  print(i)

#while loop code

user_input = ""

while user_input.lower() != "quit":
  user_input = input("Enter your value: ")

print("You entered quit")

#user defined function

def findSquare(num):
  square_val = num * num
  return square_val

answer = findSquare(11)
print("Square of number 11 is: ",answer)

def factorial(num):
  if num == 1 or num == 0:
    return 1

  return num * factorial(num-1)


result = factorial(4)
print(result)

import numpy as np
d_0 = np.array(42) #0d
d_1 = np.array([42,421,423,424]) #1d
d_2 = np.array([ #2d
 [1,2,3],
 ('t', 'u', 'p',),
 ('t', 'u', 'p',),
 ('t', 'u', 'p',),
 ('t', 'u', 'p',)
 ])

d_3 = np.array([
 [
 [1,2,3],
 [4,5,6],
 [7,8,9] ],

 [
 [10,12,14],
 [15,18,30],
 [33,35,36]
 ]
 ]
 )

print("Size of d3 is: ",d_3.size)
print("Dimensions of d3 are: ",d_3.ndim)

flattened_array = d_2.flatten()
print("Dimensions of flattened array is ",flattened_array.ndim)
print("Size of flattened array is: ",flattened_array.size)

#pandas task
import pandas as pd

df = pd.read_csv("/Data.csv")

print("Dataset Loaded Successfully")

# 1.
print("\n1. head()")
print(df.head())

# 2.
print("\n2. tail()")
print(df.tail())

# 3.
print("\n3. shape")
print(df.shape)

# 4.
print("\n4. columns")
print(df.columns)

# 5.
print("\n5. info()")
df.info()

# 6.
print("\n6. describe()")
print(df.describe())

# 7.
print("\n7. dtypes")
print(df.dtypes)

# 8.
print("\n8. value_counts() on GHG")
print(df["GHG"].value_counts())

# 9.
print("\n9. sort_values()")
print(df.sort_values(by="Supply Chain Emission Factors with Margins", ascending=False))

# 10.
print("\n10. isnull()")
print(df.isnull().sum())

#numpy task

import numpy as np

arr1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nAccessing Elements:")
print("arr1[0,0] =", arr1[0,0])
print("arr1[1,2] =", arr1[1,2])
print("arr2[0,1] =", arr2[0,1])
print("arr2[1,0] =", arr2[1,0])

# Mathematical Operations
print("\nAddition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr1 - arr2)

print("\nMultiplication:")
print(arr1 * arr2)

print("\nDivision:")
print(arr1 / arr2)

# 15 NumPy Methods

# 1
print("\n1. shape")
print(arr1.shape)

# 2
print("\n2. ndim")
print(arr1.ndim)

# 3
print("\n3. size")
print(arr1.size)

# 4
print("\n4. dtype")
print(arr1.dtype)

# 5
print("\n5. reshape")
print(arr1.reshape(3,2))

# 6
print("\n6. flatten")
print(arr1.flatten())

# 7
print("\n7. transpose")
print(arr1.T)

# 8
print("\n8. sum")
print(np.sum(arr1))

# 9
print("\n9. mean")
print(np.mean(arr1))

# 10
print("\n10. max")
print(np.max(arr1))

# 11
print("\n11. min")
print(np.min(arr1))

# 12
print("\n12. sqrt")
print(np.sqrt(arr1))

# 13
print("\n13. sort")
print(np.sort(arr1))

# 14
print("\n14. unique")
print(np.unique(arr1))

# 15
print("\n15. concatenate")
print(np.concatenate((arr1, arr2), axis=0))