# -*- coding: utf-8 -*-
"""EdunetDay2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_APL-OWOxZGf8fFr4ROmYRoy-8kgIzK
"""

#f string
city = "Delhi"
population = 40
b = "Twenty"
a = "Thirty"

print(f"The population of {city} is {population} and value of b is {b} and value of a is {a}")

#1) Dictionary
dict1 = {'names':['abc','def','ghi','jkl'],
         'rollno' :[123,456,789,101112],
         'city' :['delhi','mumbai','ahemdabad'],
         'stream' :['EC','CE','IT','ME']
         }

print(dict1['names'])
print(dict1['rollno'])
print(dict1['city'])
print(dict1['stream'])

#1
dict1.update({'city': ['delhi','mumbai','pune']})

#2
print(dict1.get("names"))

#3
print(dict1.keys())

#4
print(dict1.values())

#5
dict1.pop("city")

#2) List
list1 = ['a','b','c','d']

#1
list1.append('e')
print(list1)

#2
list1.extend(['g','h'])
print(list1)

#3
list1.insert(5,'f')
print(list1)

#4
list1.remove('h')
print(list1)

#5
print("popped element",list1.pop())
print(list1)

print(list1.index('f'))

print(list1.count('a'))

list1.append('a')
list1.sort()
print(list1)

list1.reverse()
print(list1)

print(list1.clear())
del list1

#3) Tuples
tup = (1, 2, 3, 2, 4)

print(tup.count(2))
print(tup.index(3))
print(len(tup))
print(max(tup))
print(min(tup))

#4) Sets
s = {1, 2, 3}

s.add(4)
print(s)

s.remove(2)
print(s)

s.update([5, 6])
print(s)

s.discard(10)
print(s)

copy_set = s.copy()
print(copy_set)

#if
num = 10

if num > 5:
    print("Number is greater than 5")

#if-else
age = 18

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

#if-elif-else
marks = 75

if marks >= 90:
    print("Grade A")
elif marks >= 60:
    print("Grade B")
else:
    print("Grade C")

#nested if-else
num = 15

if num > 0:
    if num % 2 == 0:
        print("Positive Even Number")
    else:
        print("Positive Odd Number")
else:
    print("Negative Number")

#break
print("Break Example ")
for i in range(1, 11):
    if i == 5:
        break
    print(i)

#continue
print("Continue Example ")
for i in range(1, 6):
    if i == 3:
        continue
    print(i)

#pass
print("Pass Example")
for i in range(1, 4):
    if i == 2:
        pass
    print(i)

#input method
name = input("Enter your name: ")
print("Hello,", name)

#range
for i in range(1, 6):
    print(i)

#len
text = "Python"
print("Length =", len(text))

#type
x = 100
print(type(x))

#for loop
for i in range(1, 6):
    print(i)

#while loop
print("\twhile loop")
count  = 0
while count <= 5:
    print(count)
    count += 1